export interface CarModel {
  slug: string;
  name: string;
  brand: string;
  category: '경차' | '준중형' | '중형' | '대형' | 'SUV' | '전기차' | '수입 세단' | '수입 SUV' | '수입 전기차';
  cc: number; // 0 for EV
  isEV: boolean;
  isImported: boolean;
  price: number; // 만원 단위
  fuelType: '휘발유' | '경유' | 'LPG' | '전기';
  fuelEfficiency: number; // km/L or km/kWh
  insurance20s: string;
  insurance30s: string;
  insurance40s: string;
  maintenanceMonthly: string;
  features: string[];
  competitors: string[]; // slugs
  emoji: string;
}

export const CAR_MODELS: CarModel[] = [
  // 경차
  {
    slug: 'morning',
    name: '기아 모닝',
    brand: '기아',
    category: '경차',
    cc: 998,
    isEV: false,
    isImported: false,
    price: 1400,
    fuelType: '휘발유',
    fuelEfficiency: 15.7,
    insurance20s: '약 80~120만 원',
    insurance30s: '약 40~60만 원',
    insurance40s: '약 35~50만 원',
    maintenanceMonthly: '약 19만 원',
    features: ['취득세 면제 (경차)', '유류세 환급 (연 30만 원)', '고속도로 통행료 50% 할인', '공영주차장 50% 할인'],
    competitors: ['ray', 'avante'],
    emoji: '🚗',
  },
  {
    slug: 'ray',
    name: '기아 레이',
    brand: '기아',
    category: '경차',
    cc: 998,
    isEV: false,
    isImported: false,
    price: 1600,
    fuelType: '휘발유',
    fuelEfficiency: 13.2,
    insurance20s: '약 85~130만 원',
    insurance30s: '약 45~65만 원',
    insurance40s: '약 38~55만 원',
    maintenanceMonthly: '약 20만 원',
    features: ['취득세 면제 (경차)', '유류세 환급 (연 30만 원)', '넓은 실내 공간 (박스카)', '고속도로 통행료 50% 할인'],
    competitors: ['morning', 'avante'],
    emoji: '🚐',
  },
  // 준중형
  {
    slug: 'avante',
    name: '현대 아반떼',
    brand: '현대',
    category: '준중형',
    cc: 1598,
    isEV: false,
    isImported: false,
    price: 2000,
    fuelType: '휘발유',
    fuelEfficiency: 14.3,
    insurance20s: '약 120~180만 원',
    insurance30s: '약 60~90만 원',
    insurance40s: '약 50~75만 원',
    maintenanceMonthly: '약 30만 원',
    features: ['가장 많이 팔리는 준중형', '합리적인 유지비', '다양한 트림 선택지', '하이브리드 모델 출시'],
    competitors: ['k3', 'sonata'],
    emoji: '🚙',
  },
  {
    slug: 'k3',
    name: '기아 K3',
    brand: '기아',
    category: '준중형',
    cc: 1598,
    isEV: false,
    isImported: false,
    price: 2100,
    fuelType: '휘발유',
    fuelEfficiency: 14.1,
    insurance20s: '약 120~180만 원',
    insurance30s: '약 60~90만 원',
    insurance40s: '약 50~75만 원',
    maintenanceMonthly: '약 30만 원',
    features: ['스포티한 디자인', '아반떼와 유사한 유지비', '합리적인 가격', '넓은 트렁크 공간'],
    competitors: ['avante', 'sonata'],
    emoji: '🚙',
  },
  // 중형
  {
    slug: 'sonata',
    name: '현대 쏘나타',
    brand: '현대',
    category: '중형',
    cc: 1999,
    isEV: false,
    isImported: false,
    price: 2800,
    fuelType: '휘발유',
    fuelEfficiency: 12.8,
    insurance20s: '약 150~220만 원',
    insurance30s: '약 80~120만 원',
    insurance40s: '약 65~100만 원',
    maintenanceMonthly: '약 38만 원',
    features: ['대한민국 대표 중형 세단', '하이브리드 모델 인기', '넓은 실내 공간', '안정적인 잔존가치'],
    competitors: ['k5', 'grandeur'],
    emoji: '🚘',
  },
  {
    slug: 'k5',
    name: '기아 K5',
    brand: '기아',
    category: '중형',
    cc: 1999,
    isEV: false,
    isImported: false,
    price: 2700,
    fuelType: '휘발유',
    fuelEfficiency: 13.0,
    insurance20s: '약 145~210만 원',
    insurance30s: '약 78~115만 원',
    insurance40s: '약 63~95만 원',
    maintenanceMonthly: '약 37만 원',
    features: ['세련된 디자인', '쏘나타와 유사한 유지비', '하이브리드 모델 출시', '합리적인 가격'],
    competitors: ['sonata', 'grandeur'],
    emoji: '🚘',
  },
  // 대형
  {
    slug: 'grandeur',
    name: '현대 그랜저',
    brand: '현대',
    category: '대형',
    cc: 2497,
    isEV: false,
    isImported: false,
    price: 3800,
    fuelType: '휘발유',
    fuelEfficiency: 11.2,
    insurance20s: '약 180~270만 원',
    insurance30s: '약 100~150만 원',
    insurance40s: '약 85~130만 원',
    maintenanceMonthly: '약 50만 원',
    features: ['대한민국 대표 대형 세단', '하이브리드 모델 인기', '높은 잔존가치', '프리미엄 편의사양'],
    competitors: ['k8', 'palisade'],
    emoji: '🚗',
  },
  {
    slug: 'k8',
    name: '기아 K8',
    brand: '기아',
    category: '대형',
    cc: 2497,
    isEV: false,
    isImported: false,
    price: 3600,
    fuelType: '휘발유',
    fuelEfficiency: 11.5,
    insurance20s: '약 175~260만 원',
    insurance30s: '약 95~145만 원',
    insurance40s: '약 80~125만 원',
    maintenanceMonthly: '약 48만 원',
    features: ['세련된 디자인', '그랜저 대비 합리적 가격', '하이브리드 모델 출시', '넓은 뒷좌석'],
    competitors: ['grandeur', 'palisade'],
    emoji: '🚗',
  },
  // SUV
  {
    slug: 'tucson',
    name: '현대 투싼',
    brand: '현대',
    category: 'SUV',
    cc: 1999,
    isEV: false,
    isImported: false,
    price: 2800,
    fuelType: '경유',
    fuelEfficiency: 14.2,
    insurance20s: '약 155~230만 원',
    insurance30s: '약 85~125만 원',
    insurance40s: '약 70~105만 원',
    maintenanceMonthly: '약 40만 원',
    features: ['가장 많이 팔리는 중형 SUV', '하이브리드 모델 인기', '넓은 적재 공간', '합리적인 유지비'],
    competitors: ['sorento', 'palisade'],
    emoji: '🚙',
  },
  {
    slug: 'sorento',
    name: '기아 쏘렌토',
    brand: '기아',
    category: 'SUV',
    cc: 2199,
    isEV: false,
    isImported: false,
    price: 3500,
    fuelType: '경유',
    fuelEfficiency: 13.5,
    insurance20s: '약 180~270만 원',
    insurance30s: '약 100~150만 원',
    insurance40s: '약 85~130만 원',
    maintenanceMonthly: '약 45만 원',
    features: ['중대형 SUV 베스트셀러', '3열 시트 옵션', '하이브리드 모델 출시', '높은 잔존가치'],
    competitors: ['tucson', 'palisade'],
    emoji: '🚙',
  },
  {
    slug: 'palisade',
    name: '현대 팰리세이드',
    brand: '현대',
    category: 'SUV',
    cc: 3498,
    isEV: false,
    isImported: false,
    price: 4200,
    fuelType: '경유',
    fuelEfficiency: 10.5,
    insurance20s: '약 220~330만 원',
    insurance30s: '약 120~180만 원',
    insurance40s: '약 100~155만 원',
    maintenanceMonthly: '약 55만 원',
    features: ['대형 SUV 1위', '3열 시트 기본', '프리미엄 편의사양', '높은 잔존가치'],
    competitors: ['sorento', 'grandeur'],
    emoji: '🚙',
  },
  // 전기차
  {
    slug: 'ioniq5',
    name: '현대 아이오닉 5',
    brand: '현대',
    category: '전기차',
    cc: 0,
    isEV: true,
    isImported: false,
    price: 4700,
    fuelType: '전기',
    fuelEfficiency: 5.1,
    insurance20s: '약 200~300만 원',
    insurance30s: '약 110~160만 원',
    insurance40s: '약 90~140만 원',
    maintenanceMonthly: '약 25만 원',
    features: ['전기차 보조금 대상', '취득세 최대 140만 원 감면', '자동차세 연 13만 원 정액', '충전비 내연기관 대비 70% 절약'],
    competitors: ['ev6', 'tesla-model-y'],
    emoji: '⚡',
  },
  {
    slug: 'ev6',
    name: '기아 EV6',
    brand: '기아',
    category: '전기차',
    cc: 0,
    isEV: true,
    isImported: false,
    price: 4800,
    fuelType: '전기',
    fuelEfficiency: 5.0,
    insurance20s: '약 210~310만 원',
    insurance30s: '약 115~165만 원',
    insurance40s: '약 95~145만 원',
    maintenanceMonthly: '약 26만 원',
    features: ['전기차 보조금 대상', '취득세 최대 140만 원 감면', '800V 초급속 충전', '자동차세 연 13만 원 정액'],
    competitors: ['ioniq5', 'tesla-model-y'],
    emoji: '⚡',
  },
  {
    slug: 'tesla-model-y',
    name: '테슬라 모델 Y',
    brand: '테슬라',
    category: '전기차',
    cc: 0,
    isEV: true,
    isImported: true,
    price: 5800,
    fuelType: '전기',
    fuelEfficiency: 5.2,
    insurance20s: '약 240~360만 원',
    insurance30s: '약 130~195만 원',
    insurance40s: '약 110~170만 원',
    maintenanceMonthly: '약 28만 원',
    features: ['전기차 보조금 대상 (일부)', '오토파일럿 기본', '슈퍼차저 네트워크', '수입차 중 보험료 높음'],
    competitors: ['ioniq5', 'ev6'],
    emoji: '⚡',
  },
  // ===== 수입차 =====
  // 벤츠
  {
    slug: 'benz-e-class',
    name: '벤츠 E클래스',
    brand: '메르세데스-벤츠',
    category: '수입 세단',
    cc: 1999,
    isEV: false,
    isImported: true,
    price: 7200,
    fuelType: '휘발유',
    fuelEfficiency: 11.5,
    insurance20s: '약 350~500만 원',
    insurance30s: '약 200~300만 원',
    insurance40s: '약 170~260만 원',
    maintenanceMonthly: '약 75만 원',
    features: ['수입차 판매 1위급', '높은 보험료 (국산 대비 2~3배)', '정비비 국산 대비 2배 이상', '높은 잔존가치'],
    competitors: ['bmw-5-series', 'audi-a6', 'grandeur'],
    emoji: '🔷',
  },
  {
    slug: 'benz-c-class',
    name: '벤츠 C클래스',
    brand: '메르세데스-벤츠',
    category: '수입 세단',
    cc: 1496,
    isEV: false,
    isImported: true,
    price: 5800,
    fuelType: '휘발유',
    fuelEfficiency: 12.8,
    insurance20s: '약 300~450만 원',
    insurance30s: '약 170~260만 원',
    insurance40s: '약 145~225만 원',
    maintenanceMonthly: '약 65만 원',
    features: ['엔트리 프리미엄 세단', '국산 중형 대비 보험료 2배', '정비비 국산 대비 2배', '높은 감가상각률'],
    competitors: ['bmw-3-series', 'audi-a4', 'sonata'],
    emoji: '🔷',
  },
  // BMW
  {
    slug: 'bmw-5-series',
    name: 'BMW 5시리즈',
    brand: 'BMW',
    category: '수입 세단',
    cc: 1998,
    isEV: false,
    isImported: true,
    price: 7000,
    fuelType: '휘발유',
    fuelEfficiency: 11.8,
    insurance20s: '약 340~490만 원',
    insurance30s: '약 195~290만 원',
    insurance40s: '약 165~250만 원',
    maintenanceMonthly: '약 72만 원',
    features: ['다이내믹 드라이빙', '벤츠 E클래스와 경쟁', '정비비 국산 대비 2배 이상', 'xDrive 사륜구동 옵션'],
    competitors: ['benz-e-class', 'audi-a6', 'grandeur'],
    emoji: '🔵',
  },
  {
    slug: 'bmw-3-series',
    name: 'BMW 3시리즈',
    brand: 'BMW',
    category: '수입 세단',
    cc: 1998,
    isEV: false,
    isImported: true,
    price: 5500,
    fuelType: '휘발유',
    fuelEfficiency: 12.5,
    insurance20s: '약 290~430만 원',
    insurance30s: '약 165~250만 원',
    insurance40s: '약 140~215만 원',
    maintenanceMonthly: '약 62만 원',
    features: ['스포츠 세단의 기준', '벤츠 C클래스와 경쟁', '정비비 국산 대비 2배', '높은 보험료'],
    competitors: ['benz-c-class', 'audi-a4', 'k5'],
    emoji: '🔵',
  },
  // 아우디
  {
    slug: 'audi-a6',
    name: '아우디 A6',
    brand: '아우디',
    category: '수입 세단',
    cc: 1984,
    isEV: false,
    isImported: true,
    price: 6800,
    fuelType: '휘발유',
    fuelEfficiency: 11.2,
    insurance20s: '약 330~480만 원',
    insurance30s: '약 190~280만 원',
    insurance40s: '약 160~245만 원',
    maintenanceMonthly: '약 70만 원',
    features: ['콰트로 사륜구동', '벤츠 E·BMW 5와 경쟁', '정비비 국산 대비 2배 이상', '높은 보험료'],
    competitors: ['benz-e-class', 'bmw-5-series', 'grandeur'],
    emoji: '⚪',
  },
  {
    slug: 'audi-a4',
    name: '아우디 A4',
    brand: '아우디',
    category: '수입 세단',
    cc: 1984,
    isEV: false,
    isImported: true,
    price: 5300,
    fuelType: '휘발유',
    fuelEfficiency: 12.3,
    insurance20s: '약 280~420만 원',
    insurance30s: '약 160~240만 원',
    insurance40s: '약 135~210만 원',
    maintenanceMonthly: '약 60만 원',
    features: ['콰트로 사륜구동 옵션', '벤츠 C·BMW 3와 경쟁', '정비비 국산 대비 2배', '합리적인 수입차 엔트리'],
    competitors: ['benz-c-class', 'bmw-3-series', 'k5'],
    emoji: '⚪',
  },
  // 볼보
  {
    slug: 'volvo-xc60',
    name: '볼보 XC60',
    brand: '볼보',
    category: '수입 SUV',
    cc: 1969,
    isEV: false,
    isImported: true,
    price: 6500,
    fuelType: '휘발유',
    fuelEfficiency: 10.8,
    insurance20s: '약 310~460만 원',
    insurance30s: '약 175~265만 원',
    insurance40s: '약 150~230만 원',
    maintenanceMonthly: '약 68만 원',
    features: ['세계 최고 수준 안전', '독일 3사 대비 합리적 가격', '정비비 국산 대비 1.5~2배', '높은 잔존가치'],
    competitors: ['benz-e-class', 'bmw-5-series', 'palisade'],
    emoji: '🔘',
  },
  // BMW 전기차
  {
    slug: 'bmw-ix',
    name: 'BMW iX',
    brand: 'BMW',
    category: '수입 전기차',
    cc: 0,
    isEV: true,
    isImported: true,
    price: 9800,
    fuelType: '전기',
    fuelEfficiency: 4.8,
    insurance20s: '약 380~550만 원',
    insurance30s: '약 220~330만 원',
    insurance40s: '약 185~285만 원',
    maintenanceMonthly: '약 45만 원',
    features: ['전기차 보조금 대상 (일부)', '취득세 최대 140만 원 감면', '자동차세 연 13만 원 정액', '수입 전기차 중 높은 보험료'],
    competitors: ['tesla-model-y', 'ioniq5', 'ev6'],
    emoji: '🔵',
  },
  // 벤츠 SUV
  {
    slug: 'benz-glc',
    name: '벤츠 GLC',
    brand: '메르세데스-벤츠',
    category: '수입 SUV',
    cc: 1999,
    isEV: false,
    isImported: true,
    price: 6300,
    fuelType: '휘발유',
    fuelEfficiency: 10.5,
    insurance20s: '약 330~480만 원',
    insurance30s: '약 190~280만 원',
    insurance40s: '약 160~245만 원',
    maintenanceMonthly: '약 72만 원',
    features: ['수입 SUV 판매 1위급', '벤츠 인기 모델', '정비비 국산 SUV 대비 2배 이상', 'AMG 라인 옵션'],
    competitors: ['bmw-x3', 'volvo-xc60', 'audi-a6'],
    emoji: '🔷',
  },
  {
    slug: 'benz-gle',
    name: '벤츠 GLE',
    brand: '메르세데스-벤츠',
    category: '수입 SUV',
    cc: 2999,
    isEV: false,
    isImported: true,
    price: 9500,
    fuelType: '휘발유',
    fuelEfficiency: 9.2,
    insurance20s: '약 400~580만 원',
    insurance30s: '약 230~340만 원',
    insurance40s: '약 195~295만 원',
    maintenanceMonthly: '약 90만 원',
    features: ['대형 프리미엄 SUV', '3열 시트 옵션 (GLE 7인승)', '정비비 국산 대비 2.5배', 'AMG GLE 53/63 라인업'],
    competitors: ['bmw-x5', 'porsche-cayenne', 'lexus-rx'],
    emoji: '🔷',
  },
  // BMW SUV
  {
    slug: 'bmw-x3',
    name: 'BMW X3',
    brand: 'BMW',
    category: '수입 SUV',
    cc: 1998,
    isEV: false,
    isImported: true,
    price: 6500,
    fuelType: '휘발유',
    fuelEfficiency: 10.8,
    insurance20s: '약 320~470만 원',
    insurance30s: '약 185~275만 원',
    insurance40s: '약 155~240만 원',
    maintenanceMonthly: '약 70만 원',
    features: ['BMW 베스트셀러 SUV', 'xDrive 사륜구동 기본', '정비비 국산 SUV 대비 2배', '스포티한 주행 성능'],
    competitors: ['benz-glc', 'volvo-xc60', 'vw-tiguan'],
    emoji: '🔵',
  },
  {
    slug: 'bmw-x5',
    name: 'BMW X5',
    brand: 'BMW',
    category: '수입 SUV',
    cc: 2998,
    isEV: false,
    isImported: true,
    price: 10000,
    fuelType: '휘발유',
    fuelEfficiency: 9.5,
    insurance20s: '약 410~590만 원',
    insurance30s: '약 235~350만 원',
    insurance40s: '약 200~305만 원',
    maintenanceMonthly: '약 92만 원',
    features: ['대형 프리미엄 SAV', 'xDrive 사륜구동 기본', '정비비 국산 대비 2.5배', 'M스포츠 패키지 인기'],
    competitors: ['benz-gle', 'porsche-cayenne', 'lexus-rx'],
    emoji: '🔵',
  },
  // 렉서스
  {
    slug: 'lexus-es',
    name: '렉서스 ES',
    brand: '렉서스',
    category: '수입 세단',
    cc: 2487,
    isEV: false,
    isImported: true,
    price: 5800,
    fuelType: '휘발유',
    fuelEfficiency: 17.2,
    insurance20s: '약 260~390만 원',
    insurance30s: '약 150~225만 원',
    insurance40s: '약 125~195만 원',
    maintenanceMonthly: '약 52만 원',
    features: ['하이브리드 기본 (뛰어난 연비)', '독일 3사 대비 낮은 정비비', '정숙성 최상급', '높은 내구성과 신뢰성'],
    competitors: ['benz-c-class', 'bmw-3-series', 'toyota-camry'],
    emoji: '🔴',
  },
  {
    slug: 'lexus-rx',
    name: '렉서스 RX',
    brand: '렉서스',
    category: '수입 SUV',
    cc: 2487,
    isEV: false,
    isImported: true,
    price: 7800,
    fuelType: '휘발유',
    fuelEfficiency: 14.5,
    insurance20s: '약 340~490만 원',
    insurance30s: '약 195~290만 원',
    insurance40s: '약 165~250만 원',
    maintenanceMonthly: '약 58만 원',
    features: ['하이브리드 SUV 대표', '독일 3사 대비 유지비 저렴', '높은 내구성과 신뢰성', '정숙한 승차감'],
    competitors: ['benz-gle', 'bmw-x5', 'volvo-xc60'],
    emoji: '🔴',
  },
  // 토요타
  {
    slug: 'toyota-camry',
    name: '토요타 캠리',
    brand: '토요타',
    category: '수입 세단',
    cc: 2487,
    isEV: false,
    isImported: true,
    price: 4200,
    fuelType: '휘발유',
    fuelEfficiency: 18.1,
    insurance20s: '약 200~300만 원',
    insurance30s: '약 115~170만 원',
    insurance40s: '약 95~145만 원',
    maintenanceMonthly: '약 40만 원',
    features: ['수입차 중 가장 낮은 유지비', '하이브리드 기본 (최고 연비)', '독일차 대비 정비비 40% 저렴', '높은 내구성과 잔존가치'],
    competitors: ['lexus-es', 'sonata', 'k5'],
    emoji: '🔴',
  },
  // 폭스바겐
  {
    slug: 'vw-tiguan',
    name: '폭스바겐 티구안',
    brand: '폭스바겐',
    category: '수입 SUV',
    cc: 1984,
    isEV: false,
    isImported: true,
    price: 5000,
    fuelType: '휘발유',
    fuelEfficiency: 11.5,
    insurance20s: '약 270~400만 원',
    insurance30s: '약 155~230만 원',
    insurance40s: '약 130~200만 원',
    maintenanceMonthly: '약 55만 원',
    features: ['합리적인 가격의 수입 SUV', '4MOTION 사륜구동', '독일 3사 대비 저렴한 정비비', '넓은 실내 공간'],
    competitors: ['bmw-x3', 'benz-glc', 'tucson'],
    emoji: '🟡',
  },
  // 포르쉐
  {
    slug: 'porsche-cayenne',
    name: '포르쉐 카이엔',
    brand: '포르쉐',
    category: '수입 SUV',
    cc: 2995,
    isEV: false,
    isImported: true,
    price: 13000,
    fuelType: '휘발유',
    fuelEfficiency: 8.5,
    insurance20s: '약 520~750만 원',
    insurance30s: '약 300~440만 원',
    insurance40s: '약 250~380만 원',
    maintenanceMonthly: '약 120만 원',
    features: ['스포츠카 DNA의 럭셔리 SUV', '보험료 수입차 중 최고 수준', '정비비 국산 대비 3배 이상', 'S/GTS/터보 라인업'],
    competitors: ['benz-gle', 'bmw-x5', 'lexus-rx'],
    emoji: '🔶',
  },
  // 미니
  {
    slug: 'mini-cooper',
    name: '미니 쿠퍼',
    brand: 'MINI',
    category: '수입 세단',
    cc: 1499,
    isEV: false,
    isImported: true,
    price: 3800,
    fuelType: '휘발유',
    fuelEfficiency: 13.5,
    insurance20s: '약 220~330만 원',
    insurance30s: '약 125~190만 원',
    insurance40s: '약 105~165만 원',
    maintenanceMonthly: '약 50만 원',
    features: ['개성적인 디자인', '가장 저렴한 수입차 중 하나', 'BMW 엔진 공유 (신뢰성)', '보험료 수입차 중 합리적'],
    competitors: ['bmw-3-series', 'audi-a4', 'benz-c-class'],
    emoji: '🟢',
  },
];

export function getCarModel(slug: string): CarModel | undefined {
  return CAR_MODELS.find((m) => m.slug === slug);
}

export function getAllSlugs(): string[] {
  return CAR_MODELS.map((m) => m.slug);
}
